name: virtual_traveller_flutter
description: Travel virtually and discover interesting destinations.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2 # https://pub.dev/packages/http
  rxdart: ^0.24.1 # https://pub.dev/packages/rxdart https://rxmarbles.com/
  equatable: ^1.2.5 # https://pub.dev/packages/equatable
  flutter_bloc: ^6.1.0 # https://pub.dev/packages/flutter_bloc https://bloclibrary.dev/#/
  bloc_test: ^7.1.0 # https://pub.dev/packages/bloc_test
  mockito: ^4.1.3 # https://pub.dev/packages/mockito
  freezed: ^0.12.2 # https://pub.dev/packages/freezed
  json_serializable: ^3.5.0 # https://pub.dev/packages/json_serializable
  shared_preferences: ^0.5.12+4 # https://pub.dev/packages/shared_preferences
  url_launcher: ^5.7.10 # https://pub.dev/packages/url_launcher
  geolocator: ^6.1.5 # https://pub.dev/packages/geolocator

  # ui related
  clean_settings: ^0.1.5 # https://pub.dev/packages/clean_settings
  flutter_typeahead: ^1.8.8 # https://pub.dev/packages/flutter_typeahead
  shimmer: ^1.1.2 # https://pub.dev/packages/shimmer
  flutter_svg: ^0.19.1
#  intro_slider: ^2.3.3 # https://pub.dev/packages/intro_slider
#  responsive_builder: ^0.3.0 # https://pub.dev/packages/responsive_builder
#  auto_size_text: ^2.1.0 # https://pub.dev/packages/auto_size_text
#  syncfusion_flutter_datepicker: ^18.2.57-beta # https://pub.dev/packages/syncfusion_flutter_datepicker
#  animations: ^1.1.2 # https://pub.dev/packages/animations


# flutter pub run build_runner build --delete-conflicting-outputs
# flutter pub run build_runner watch
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.2 # https://pub.dev/packages/pedantic
  build_runner: ^1.10.4 # https://pub.dev/packages/build_runner

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
