on: [push, pull_request]
name: Tests, Build apk
jobs:
  build:
    name: Run tests & build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.4'
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
    - name: Build apk
      run: flutter build apk
